### ISSUE TITLE
No bed leveling

### ISSUE THREAD

**Issue by 0cwa** [3d-printing-canada/Ender-3-BL-Touch-Installation#1]
The bltouch works as a z stop switch, but there's no bed leveling command nor does it bed level when the start code runs.

**Comment by GhostlyCrowd** [comment]
yes, correct. whats the bug or question?

**Comment by 0cwa** [comment]
Shouldn't it have a bed leveling command?

**Comment by GhostlyCrowd** [comment]
You need to tell it to level the bed. the printer will never do anything unless its told to do so. 

https://marlinfw.org/docs/gcode/G029-abl.html

**Comment by 0cwa** [comment]
Ok, nevermind, my last firmware had a option in the menu to run G029, but that'll work, thanks.
